//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


class bcPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="SWIGRegisterExceptionCallbacks_bc")]
    public static extern void SWIGRegisterExceptionCallbacks_bc(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_bc")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_bc(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_bc(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_bc(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(typeof(bcPINVOKE)) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(typeof(bcPINVOKE)) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="SWIGRegisterStringCallback_bc")]
    public static extern void SWIGRegisterStringCallback_bc(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_bc(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static bcPINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Planet_other")]
  public static extern int Planet_other(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Planet_debug")]
  public static extern string Planet_debug(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Planet_eq")]
  public static extern byte Planet_eq(int jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Planet_from_json")]
  public static extern int Planet_from_json(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Planet_to_json")]
  public static extern string Planet_to_json(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Direction_dx")]
  public static extern int Direction_dx(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Direction_dy")]
  public static extern int Direction_dy(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Direction_is_diagonal")]
  public static extern byte Direction_is_diagonal(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Direction_opposite")]
  public static extern int Direction_opposite(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Direction_rotate_left")]
  public static extern int Direction_rotate_left(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Direction_rotate_right")]
  public static extern int Direction_rotate_right(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Direction_from_json")]
  public static extern int Direction_from_json(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Direction_to_json")]
  public static extern string Direction_to_json(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_new_MapLocation")]
  public static extern global::System.IntPtr new_MapLocation(int jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_delete_MapLocation")]
  public static extern void delete_MapLocation(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_MapLocation_add")]
  public static extern global::System.IntPtr MapLocation_add(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_MapLocation_subtract")]
  public static extern global::System.IntPtr MapLocation_subtract(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_MapLocation_add_multiple")]
  public static extern global::System.IntPtr MapLocation_add_multiple(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_MapLocation_translate")]
  public static extern global::System.IntPtr MapLocation_translate(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_MapLocation_distance_squared_to")]
  public static extern uint MapLocation_distance_squared_to(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_MapLocation_direction_to")]
  public static extern int MapLocation_direction_to(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_MapLocation_is_adjacent_to")]
  public static extern byte MapLocation_is_adjacent_to(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_MapLocation_is_within_range")]
  public static extern byte MapLocation_is_within_range(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_MapLocation_debug")]
  public static extern string MapLocation_debug(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_MapLocation_clone")]
  public static extern global::System.IntPtr MapLocation_clone(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_MapLocation_eq")]
  public static extern byte MapLocation_eq(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_MapLocation_to_json")]
  public static extern string MapLocation_to_json(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_MapLocation_planet_set")]
  public static extern void MapLocation_planet_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_MapLocation_planet_get")]
  public static extern int MapLocation_planet_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_MapLocation_x_set")]
  public static extern void MapLocation_x_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_MapLocation_x_get")]
  public static extern int MapLocation_x_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_MapLocation_y_set")]
  public static extern void MapLocation_y_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_MapLocation_y_get")]
  public static extern int MapLocation_y_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_MapLocation_from_json")]
  public static extern global::System.IntPtr MapLocation_from_json(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_new_VecMapLocation")]
  public static extern global::System.IntPtr new_VecMapLocation();

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_delete_VecMapLocation")]
  public static extern void delete_VecMapLocation(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_VecMapLocation_debug")]
  public static extern string VecMapLocation_debug(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_VecMapLocation_clone")]
  public static extern global::System.IntPtr VecMapLocation_clone(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_VecMapLocation_len")]
  public static extern uint VecMapLocation_len(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_VecMapLocation_index")]
  public static extern global::System.IntPtr VecMapLocation_index(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_new_Veci32")]
  public static extern global::System.IntPtr new_Veci32();

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_delete_Veci32")]
  public static extern void delete_Veci32(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Veci32_debug")]
  public static extern string Veci32_debug(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Veci32_clone")]
  public static extern global::System.IntPtr Veci32_clone(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Veci32_len")]
  public static extern uint Veci32_len(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Veci32_index")]
  public static extern int Veci32_index(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_new_Location")]
  public static extern global::System.IntPtr new_Location();

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_delete_Location")]
  public static extern void delete_Location(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Location_is_on_map")]
  public static extern byte Location_is_on_map(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Location_is_on_planet")]
  public static extern byte Location_is_on_planet(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Location_map_location")]
  public static extern global::System.IntPtr Location_map_location(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Location_is_in_garrison")]
  public static extern byte Location_is_in_garrison(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Location_structure")]
  public static extern ushort Location_structure(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Location_is_in_space")]
  public static extern byte Location_is_in_space(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Location_is_adjacent_to")]
  public static extern byte Location_is_adjacent_to(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Location_is_within_range")]
  public static extern byte Location_is_within_range(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Location_debug")]
  public static extern string Location_debug(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Location_clone")]
  public static extern global::System.IntPtr Location_clone(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Location_eq")]
  public static extern byte Location_eq(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Location_to_json")]
  public static extern string Location_to_json(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Location_new_on_map")]
  public static extern global::System.IntPtr Location_new_on_map(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Location_new_in_garrison")]
  public static extern global::System.IntPtr Location_new_in_garrison(ushort jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Location_new_in_space")]
  public static extern global::System.IntPtr Location_new_in_space();

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Location_from_json")]
  public static extern global::System.IntPtr Location_from_json(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Team_from_json")]
  public static extern int Team_from_json(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Team_to_json")]
  public static extern string Team_to_json(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_new_Player")]
  public static extern global::System.IntPtr new_Player(int jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_delete_Player")]
  public static extern void delete_Player(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Player_debug")]
  public static extern string Player_debug(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Player_clone")]
  public static extern global::System.IntPtr Player_clone(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Player_eq")]
  public static extern byte Player_eq(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Player_to_json")]
  public static extern string Player_to_json(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Player_team_set")]
  public static extern void Player_team_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Player_team_get")]
  public static extern int Player_team_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Player_planet_set")]
  public static extern void Player_planet_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Player_planet_get")]
  public static extern int Player_planet_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Player_from_json")]
  public static extern global::System.IntPtr Player_from_json(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_new_VecUnitID")]
  public static extern global::System.IntPtr new_VecUnitID();

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_delete_VecUnitID")]
  public static extern void delete_VecUnitID(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_VecUnitID_debug")]
  public static extern string VecUnitID_debug(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_VecUnitID_clone")]
  public static extern global::System.IntPtr VecUnitID_clone(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_VecUnitID_len")]
  public static extern uint VecUnitID_len(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_VecUnitID_index")]
  public static extern ushort VecUnitID_index(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_UnitType_from_json")]
  public static extern int UnitType_from_json(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_UnitType_to_json")]
  public static extern string UnitType_to_json(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_UnitType_factory_cost")]
  public static extern uint UnitType_factory_cost(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_UnitType_blueprint_cost")]
  public static extern uint UnitType_blueprint_cost(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_UnitType_replicate_cost")]
  public static extern uint UnitType_replicate_cost(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_UnitType_value")]
  public static extern uint UnitType_value(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_new_VecUnitType")]
  public static extern global::System.IntPtr new_VecUnitType();

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_delete_VecUnitType")]
  public static extern void delete_VecUnitType(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_VecUnitType_debug")]
  public static extern string VecUnitType_debug(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_VecUnitType_clone")]
  public static extern global::System.IntPtr VecUnitType_clone(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_VecUnitType_len")]
  public static extern uint VecUnitType_len(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_VecUnitType_index")]
  public static extern int VecUnitType_index(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_new_Unit")]
  public static extern global::System.IntPtr new_Unit();

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_delete_Unit")]
  public static extern void delete_Unit(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Unit_debug")]
  public static extern string Unit_debug(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Unit_clone")]
  public static extern global::System.IntPtr Unit_clone(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Unit_to_json")]
  public static extern string Unit_to_json(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Unit_eq")]
  public static extern byte Unit_eq(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Unit_id")]
  public static extern ushort Unit_id(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Unit_team")]
  public static extern int Unit_team(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Unit_research_level")]
  public static extern uint Unit_research_level(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Unit_unit_type")]
  public static extern int Unit_unit_type(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Unit_location")]
  public static extern global::System.IntPtr Unit_location(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Unit_health")]
  public static extern uint Unit_health(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Unit_max_health")]
  public static extern uint Unit_max_health(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Unit_vision_range")]
  public static extern uint Unit_vision_range(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Unit_damage")]
  public static extern int Unit_damage(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Unit_attack_range")]
  public static extern uint Unit_attack_range(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Unit_movement_heat")]
  public static extern uint Unit_movement_heat(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Unit_attack_heat")]
  public static extern uint Unit_attack_heat(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Unit_movement_cooldown")]
  public static extern uint Unit_movement_cooldown(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Unit_attack_cooldown")]
  public static extern uint Unit_attack_cooldown(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Unit_is_ability_unlocked")]
  public static extern byte Unit_is_ability_unlocked(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Unit_ability_heat")]
  public static extern uint Unit_ability_heat(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Unit_ability_cooldown")]
  public static extern uint Unit_ability_cooldown(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Unit_ability_range")]
  public static extern uint Unit_ability_range(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Unit_worker_has_acted")]
  public static extern byte Unit_worker_has_acted(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Unit_worker_build_health")]
  public static extern uint Unit_worker_build_health(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Unit_worker_repair_health")]
  public static extern uint Unit_worker_repair_health(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Unit_worker_harvest_amount")]
  public static extern uint Unit_worker_harvest_amount(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Unit_knight_defense")]
  public static extern uint Unit_knight_defense(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Unit_ranger_cannot_attack_range")]
  public static extern uint Unit_ranger_cannot_attack_range(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Unit_ranger_max_countdown")]
  public static extern uint Unit_ranger_max_countdown(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Unit_ranger_is_sniping")]
  public static extern byte Unit_ranger_is_sniping(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Unit_ranger_target_location")]
  public static extern global::System.IntPtr Unit_ranger_target_location(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Unit_ranger_countdown")]
  public static extern uint Unit_ranger_countdown(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Unit_healer_self_heal_amount")]
  public static extern uint Unit_healer_self_heal_amount(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Unit_structure_is_built")]
  public static extern byte Unit_structure_is_built(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Unit_structure_max_capacity")]
  public static extern uint Unit_structure_max_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Unit_structure_garrison")]
  public static extern global::System.IntPtr Unit_structure_garrison(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Unit_is_factory_producing")]
  public static extern byte Unit_is_factory_producing(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Unit_factory_unit_type")]
  public static extern int Unit_factory_unit_type(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Unit_factory_rounds_left")]
  public static extern uint Unit_factory_rounds_left(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Unit_factory_max_rounds_left")]
  public static extern uint Unit_factory_max_rounds_left(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Unit_rocket_is_used")]
  public static extern byte Unit_rocket_is_used(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Unit_rocket_blast_damage")]
  public static extern int Unit_rocket_blast_damage(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Unit_rocket_travel_time_decrease")]
  public static extern uint Unit_rocket_travel_time_decrease(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Unit_from_json")]
  public static extern global::System.IntPtr Unit_from_json(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_new_VecUnit")]
  public static extern global::System.IntPtr new_VecUnit();

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_delete_VecUnit")]
  public static extern void delete_VecUnit(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_VecUnit_debug")]
  public static extern string VecUnit_debug(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_VecUnit_clone")]
  public static extern global::System.IntPtr VecUnit_clone(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_VecUnit_len")]
  public static extern uint VecUnit_len(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_VecUnit_index")]
  public static extern global::System.IntPtr VecUnit_index(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_new_PlanetMap")]
  public static extern global::System.IntPtr new_PlanetMap();

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_delete_PlanetMap")]
  public static extern void delete_PlanetMap(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_PlanetMap_validate")]
  public static extern void PlanetMap_validate(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_PlanetMap_on_map")]
  public static extern byte PlanetMap_on_map(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_PlanetMap_is_passable_terrain_at")]
  public static extern byte PlanetMap_is_passable_terrain_at(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_PlanetMap_initial_karbonite_at")]
  public static extern uint PlanetMap_initial_karbonite_at(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_PlanetMap_clone")]
  public static extern global::System.IntPtr PlanetMap_clone(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_PlanetMap_to_json")]
  public static extern string PlanetMap_to_json(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_PlanetMap_planet_set")]
  public static extern void PlanetMap_planet_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_PlanetMap_planet_get")]
  public static extern int PlanetMap_planet_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_PlanetMap_height_set")]
  public static extern void PlanetMap_height_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_PlanetMap_height_get")]
  public static extern uint PlanetMap_height_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_PlanetMap_width_set")]
  public static extern void PlanetMap_width_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_PlanetMap_width_get")]
  public static extern uint PlanetMap_width_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_PlanetMap_initial_units_set")]
  public static extern void PlanetMap_initial_units_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_PlanetMap_initial_units_get")]
  public static extern global::System.IntPtr PlanetMap_initial_units_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_PlanetMap_from_json")]
  public static extern global::System.IntPtr PlanetMap_from_json(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_new_Delta")]
  public static extern global::System.IntPtr new_Delta();

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_delete_Delta")]
  public static extern void delete_Delta(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Delta_to_json")]
  public static extern string Delta_to_json(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_Delta_from_json")]
  public static extern global::System.IntPtr Delta_from_json(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_new_StartGameMessage")]
  public static extern global::System.IntPtr new_StartGameMessage();

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_delete_StartGameMessage")]
  public static extern void delete_StartGameMessage(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_StartGameMessage_to_json")]
  public static extern string StartGameMessage_to_json(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_StartGameMessage_from_json")]
  public static extern global::System.IntPtr StartGameMessage_from_json(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_new_TurnMessage")]
  public static extern global::System.IntPtr new_TurnMessage();

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_delete_TurnMessage")]
  public static extern void delete_TurnMessage(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_TurnMessage_to_json")]
  public static extern string TurnMessage_to_json(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_TurnMessage_from_json")]
  public static extern global::System.IntPtr TurnMessage_from_json(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_new_StartTurnMessage")]
  public static extern global::System.IntPtr new_StartTurnMessage();

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_delete_StartTurnMessage")]
  public static extern void delete_StartTurnMessage(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_StartTurnMessage_to_json")]
  public static extern string StartTurnMessage_to_json(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_StartTurnMessage_round_set")]
  public static extern void StartTurnMessage_round_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_StartTurnMessage_round_get")]
  public static extern uint StartTurnMessage_round_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_StartTurnMessage_from_json")]
  public static extern global::System.IntPtr StartTurnMessage_from_json(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_new_ViewerMessage")]
  public static extern global::System.IntPtr new_ViewerMessage();

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_delete_ViewerMessage")]
  public static extern void delete_ViewerMessage(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_ViewerMessage_to_json")]
  public static extern string ViewerMessage_to_json(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_ViewerMessage_from_json")]
  public static extern global::System.IntPtr ViewerMessage_from_json(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_new_ViewerKeyframe")]
  public static extern global::System.IntPtr new_ViewerKeyframe();

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_delete_ViewerKeyframe")]
  public static extern void delete_ViewerKeyframe(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_ViewerKeyframe_to_json")]
  public static extern string ViewerKeyframe_to_json(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_ViewerKeyframe_from_json")]
  public static extern global::System.IntPtr ViewerKeyframe_from_json(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_new_ErrorMessage")]
  public static extern global::System.IntPtr new_ErrorMessage();

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_delete_ErrorMessage")]
  public static extern void delete_ErrorMessage(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_ErrorMessage_to_json")]
  public static extern string ErrorMessage_to_json(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_ErrorMessage_debug")]
  public static extern string ErrorMessage_debug(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_ErrorMessage_error_set")]
  public static extern void ErrorMessage_error_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_ErrorMessage_error_get")]
  public static extern string ErrorMessage_error_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_ErrorMessage_from_json")]
  public static extern global::System.IntPtr ErrorMessage_from_json(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_new_TurnApplication")]
  public static extern global::System.IntPtr new_TurnApplication();

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_delete_TurnApplication")]
  public static extern void delete_TurnApplication(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_TurnApplication_start_turn_set")]
  public static extern void TurnApplication_start_turn_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_TurnApplication_start_turn_get")]
  public static extern global::System.IntPtr TurnApplication_start_turn_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_TurnApplication_viewer_set")]
  public static extern void TurnApplication_viewer_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_TurnApplication_viewer_get")]
  public static extern global::System.IntPtr TurnApplication_viewer_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_new_InitialTurnApplication")]
  public static extern global::System.IntPtr new_InitialTurnApplication();

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_delete_InitialTurnApplication")]
  public static extern void delete_InitialTurnApplication(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_InitialTurnApplication_start_turn_set")]
  public static extern void InitialTurnApplication_start_turn_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_InitialTurnApplication_start_turn_get")]
  public static extern global::System.IntPtr InitialTurnApplication_start_turn_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_InitialTurnApplication_viewer_set")]
  public static extern void InitialTurnApplication_viewer_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_InitialTurnApplication_viewer_get")]
  public static extern global::System.IntPtr InitialTurnApplication_viewer_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_new_AsteroidStrike")]
  public static extern global::System.IntPtr new_AsteroidStrike(uint jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_delete_AsteroidStrike")]
  public static extern void delete_AsteroidStrike(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_AsteroidStrike_clone")]
  public static extern global::System.IntPtr AsteroidStrike_clone(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_AsteroidStrike_debug")]
  public static extern string AsteroidStrike_debug(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_AsteroidStrike_to_json")]
  public static extern string AsteroidStrike_to_json(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_AsteroidStrike_eq")]
  public static extern byte AsteroidStrike_eq(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_AsteroidStrike_karbonite_set")]
  public static extern void AsteroidStrike_karbonite_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_AsteroidStrike_karbonite_get")]
  public static extern uint AsteroidStrike_karbonite_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_AsteroidStrike_location_set")]
  public static extern void AsteroidStrike_location_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_AsteroidStrike_location_get")]
  public static extern global::System.IntPtr AsteroidStrike_location_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_AsteroidStrike_from_json")]
  public static extern global::System.IntPtr AsteroidStrike_from_json(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_new_AsteroidPattern")]
  public static extern global::System.IntPtr new_AsteroidPattern(ushort jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_delete_AsteroidPattern")]
  public static extern void delete_AsteroidPattern(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_AsteroidPattern_validate")]
  public static extern void AsteroidPattern_validate(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_AsteroidPattern_has_asteroid")]
  public static extern byte AsteroidPattern_has_asteroid(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_AsteroidPattern_asteroid")]
  public static extern global::System.IntPtr AsteroidPattern_asteroid(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_AsteroidPattern_clone")]
  public static extern global::System.IntPtr AsteroidPattern_clone(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_AsteroidPattern_debug")]
  public static extern string AsteroidPattern_debug(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_AsteroidPattern_to_json")]
  public static extern string AsteroidPattern_to_json(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_AsteroidPattern_from_json")]
  public static extern global::System.IntPtr AsteroidPattern_from_json(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_new_OrbitPattern")]
  public static extern global::System.IntPtr new_OrbitPattern(uint jarg1, uint jarg2, uint jarg3);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_delete_OrbitPattern")]
  public static extern void delete_OrbitPattern(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_OrbitPattern_validate")]
  public static extern void OrbitPattern_validate(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_OrbitPattern_duration")]
  public static extern uint OrbitPattern_duration(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_OrbitPattern_to_json")]
  public static extern string OrbitPattern_to_json(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_OrbitPattern_amplitude_set")]
  public static extern void OrbitPattern_amplitude_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_OrbitPattern_amplitude_get")]
  public static extern uint OrbitPattern_amplitude_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_OrbitPattern_period_set")]
  public static extern void OrbitPattern_period_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_OrbitPattern_period_get")]
  public static extern uint OrbitPattern_period_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_OrbitPattern_center_set")]
  public static extern void OrbitPattern_center_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_OrbitPattern_center_get")]
  public static extern uint OrbitPattern_center_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_OrbitPattern_from_json")]
  public static extern global::System.IntPtr OrbitPattern_from_json(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_new_GameMap")]
  public static extern global::System.IntPtr new_GameMap();

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_delete_GameMap")]
  public static extern void delete_GameMap(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameMap_validate")]
  public static extern void GameMap_validate(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameMap_clone")]
  public static extern global::System.IntPtr GameMap_clone(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameMap_to_json")]
  public static extern string GameMap_to_json(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameMap_seed_set")]
  public static extern void GameMap_seed_set(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameMap_seed_get")]
  public static extern ushort GameMap_seed_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameMap_earth_map_set")]
  public static extern void GameMap_earth_map_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameMap_earth_map_get")]
  public static extern global::System.IntPtr GameMap_earth_map_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameMap_mars_map_set")]
  public static extern void GameMap_mars_map_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameMap_mars_map_get")]
  public static extern global::System.IntPtr GameMap_mars_map_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameMap_asteroids_set")]
  public static extern void GameMap_asteroids_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameMap_asteroids_get")]
  public static extern global::System.IntPtr GameMap_asteroids_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameMap_orbit_set")]
  public static extern void GameMap_orbit_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameMap_orbit_get")]
  public static extern global::System.IntPtr GameMap_orbit_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameMap_test_map")]
  public static extern global::System.IntPtr GameMap_test_map();

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameMap_from_json")]
  public static extern global::System.IntPtr GameMap_from_json(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_max_level")]
  public static extern uint max_level(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_cost_of")]
  public static extern uint cost_of(int jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_new_ResearchInfo")]
  public static extern global::System.IntPtr new_ResearchInfo();

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_delete_ResearchInfo")]
  public static extern void delete_ResearchInfo(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_ResearchInfo_get_level")]
  public static extern uint ResearchInfo_get_level(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_ResearchInfo_queue")]
  public static extern global::System.IntPtr ResearchInfo_queue(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_ResearchInfo_has_next_in_queue")]
  public static extern byte ResearchInfo_has_next_in_queue(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_ResearchInfo_next_in_queue")]
  public static extern int ResearchInfo_next_in_queue(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_ResearchInfo_rounds_left")]
  public static extern uint ResearchInfo_rounds_left(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_ResearchInfo_to_json")]
  public static extern string ResearchInfo_to_json(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_ResearchInfo_from_json")]
  public static extern global::System.IntPtr ResearchInfo_from_json(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_new_RocketLanding")]
  public static extern global::System.IntPtr new_RocketLanding(ushort jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_delete_RocketLanding")]
  public static extern void delete_RocketLanding(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_RocketLanding_clone")]
  public static extern global::System.IntPtr RocketLanding_clone(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_RocketLanding_debug")]
  public static extern string RocketLanding_debug(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_RocketLanding_to_json")]
  public static extern string RocketLanding_to_json(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_RocketLanding_eq")]
  public static extern byte RocketLanding_eq(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_RocketLanding_rocket_id_set")]
  public static extern void RocketLanding_rocket_id_set(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_RocketLanding_rocket_id_get")]
  public static extern ushort RocketLanding_rocket_id_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_RocketLanding_destination_set")]
  public static extern void RocketLanding_destination_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_RocketLanding_destination_get")]
  public static extern global::System.IntPtr RocketLanding_destination_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_RocketLanding_from_json")]
  public static extern global::System.IntPtr RocketLanding_from_json(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_new_VecRocketLanding")]
  public static extern global::System.IntPtr new_VecRocketLanding();

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_delete_VecRocketLanding")]
  public static extern void delete_VecRocketLanding(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_VecRocketLanding_debug")]
  public static extern string VecRocketLanding_debug(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_VecRocketLanding_clone")]
  public static extern global::System.IntPtr VecRocketLanding_clone(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_VecRocketLanding_len")]
  public static extern uint VecRocketLanding_len(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_VecRocketLanding_index")]
  public static extern global::System.IntPtr VecRocketLanding_index(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_new_RocketLandingInfo")]
  public static extern global::System.IntPtr new_RocketLandingInfo();

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_delete_RocketLandingInfo")]
  public static extern void delete_RocketLandingInfo(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_RocketLandingInfo_landings_on")]
  public static extern global::System.IntPtr RocketLandingInfo_landings_on(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_RocketLandingInfo_clone")]
  public static extern global::System.IntPtr RocketLandingInfo_clone(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_RocketLandingInfo_debug")]
  public static extern string RocketLandingInfo_debug(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_RocketLandingInfo_to_json")]
  public static extern string RocketLandingInfo_to_json(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_RocketLandingInfo_eq")]
  public static extern byte RocketLandingInfo_eq(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_RocketLandingInfo_from_json")]
  public static extern global::System.IntPtr RocketLandingInfo_from_json(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_new_GameController")]
  public static extern global::System.IntPtr new_GameController();

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_delete_GameController")]
  public static extern void delete_GameController(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_next_turn")]
  public static extern void GameController_next_turn(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_round")]
  public static extern uint GameController_round(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_planet")]
  public static extern int GameController_planet(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_team")]
  public static extern int GameController_team(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_starting_map")]
  public static extern global::System.IntPtr GameController_starting_map(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_karbonite")]
  public static extern uint GameController_karbonite(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_unit")]
  public static extern global::System.IntPtr GameController_unit(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_units")]
  public static extern global::System.IntPtr GameController_units(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_my_units")]
  public static extern global::System.IntPtr GameController_my_units(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_units_in_space")]
  public static extern global::System.IntPtr GameController_units_in_space(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_karbonite_at")]
  public static extern uint GameController_karbonite_at(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_all_locations_within")]
  public static extern global::System.IntPtr GameController_all_locations_within(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, uint jarg3);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_can_sense_location")]
  public static extern byte GameController_can_sense_location(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_can_sense_unit")]
  public static extern byte GameController_can_sense_unit(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_sense_nearby_units")]
  public static extern global::System.IntPtr GameController_sense_nearby_units(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, uint jarg3);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_sense_nearby_units_by_team")]
  public static extern global::System.IntPtr GameController_sense_nearby_units_by_team(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, uint jarg3, int jarg4);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_sense_nearby_units_by_type")]
  public static extern global::System.IntPtr GameController_sense_nearby_units_by_type(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, uint jarg3, int jarg4);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_has_unit_at_location")]
  public static extern byte GameController_has_unit_at_location(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_sense_unit_at_location")]
  public static extern global::System.IntPtr GameController_sense_unit_at_location(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_asteroid_pattern")]
  public static extern global::System.IntPtr GameController_asteroid_pattern(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_orbit_pattern")]
  public static extern global::System.IntPtr GameController_orbit_pattern(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_current_duration_of_flight")]
  public static extern uint GameController_current_duration_of_flight(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_get_team_array")]
  public static extern global::System.IntPtr GameController_get_team_array(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_write_team_array")]
  public static extern void GameController_write_team_array(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_disintegrate_unit")]
  public static extern void GameController_disintegrate_unit(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_is_occupiable")]
  public static extern byte GameController_is_occupiable(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_can_move")]
  public static extern byte GameController_can_move(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_is_move_ready")]
  public static extern byte GameController_is_move_ready(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_move_robot")]
  public static extern void GameController_move_robot(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_can_attack")]
  public static extern byte GameController_can_attack(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2, ushort jarg3);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_is_attack_ready")]
  public static extern byte GameController_is_attack_ready(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_attack")]
  public static extern void GameController_attack(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2, ushort jarg3);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_research_info")]
  public static extern global::System.IntPtr GameController_research_info(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_reset_research")]
  public static extern byte GameController_reset_research(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_queue_research")]
  public static extern byte GameController_queue_research(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_can_harvest")]
  public static extern byte GameController_can_harvest(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_harvest")]
  public static extern void GameController_harvest(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_can_blueprint")]
  public static extern byte GameController_can_blueprint(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2, int jarg3, int jarg4);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_blueprint")]
  public static extern void GameController_blueprint(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2, int jarg3, int jarg4);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_can_build")]
  public static extern byte GameController_can_build(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2, ushort jarg3);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_build")]
  public static extern void GameController_build(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2, ushort jarg3);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_can_repair")]
  public static extern byte GameController_can_repair(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2, ushort jarg3);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_repair")]
  public static extern void GameController_repair(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2, ushort jarg3);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_can_replicate")]
  public static extern byte GameController_can_replicate(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_replicate")]
  public static extern void GameController_replicate(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_can_javelin")]
  public static extern byte GameController_can_javelin(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2, ushort jarg3);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_is_javelin_ready")]
  public static extern byte GameController_is_javelin_ready(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_javelin")]
  public static extern void GameController_javelin(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2, ushort jarg3);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_can_begin_snipe")]
  public static extern byte GameController_can_begin_snipe(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_is_begin_snipe_ready")]
  public static extern byte GameController_is_begin_snipe_ready(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_begin_snipe")]
  public static extern void GameController_begin_snipe(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_can_blink")]
  public static extern byte GameController_can_blink(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_is_blink_ready")]
  public static extern byte GameController_is_blink_ready(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_blink")]
  public static extern void GameController_blink(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_can_heal")]
  public static extern byte GameController_can_heal(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2, ushort jarg3);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_is_heal_ready")]
  public static extern byte GameController_is_heal_ready(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_heal")]
  public static extern void GameController_heal(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2, ushort jarg3);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_can_overcharge")]
  public static extern byte GameController_can_overcharge(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2, ushort jarg3);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_is_overcharge_ready")]
  public static extern byte GameController_is_overcharge_ready(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_overcharge")]
  public static extern void GameController_overcharge(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2, ushort jarg3);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_can_load")]
  public static extern byte GameController_can_load(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2, ushort jarg3);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_load")]
  public static extern void GameController_load(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2, ushort jarg3);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_can_unload")]
  public static extern byte GameController_can_unload(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_unload")]
  public static extern void GameController_unload(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_can_produce_robot")]
  public static extern byte GameController_can_produce_robot(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_produce_robot")]
  public static extern void GameController_produce_robot(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_rocket_landings")]
  public static extern global::System.IntPtr GameController_rocket_landings(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_can_launch_rocket")]
  public static extern byte GameController_can_launch_rocket(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_launch_rocket")]
  public static extern void GameController_launch_rocket(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_start_game")]
  public static extern global::System.IntPtr GameController_start_game(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_apply_turn")]
  public static extern global::System.IntPtr GameController_apply_turn(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_initial_start_turn_message")]
  public static extern global::System.IntPtr GameController_initial_start_turn_message(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_is_over")]
  public static extern byte GameController_is_over(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_winning_team")]
  public static extern int GameController_winning_team(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_manager_viewer_message")]
  public static extern string GameController_manager_viewer_message(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("bc", EntryPoint="CSharp_GameController_new_manager")]
  public static extern global::System.IntPtr GameController_new_manager(global::System.Runtime.InteropServices.HandleRef jarg1);
}
