//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum Direction {
  North = 0,
  Northeast = 1,
  East = 2,
  Southeast = 3,
  South = 4,
  Southwest = 5,
  West = 6,
  Northwest = 7,
  Center = 8
}
