//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum UnitType {
  Worker = 0,
  Knight = 1,
  Ranger = 2,
  Mage = 3,
  Healer = 4,
  Factory = 5,
  Rocket = 6
}
